### ISSUE TITLE
Only highlights if there is a character after anchor

### ISSUE THREAD

**Issue by GammaGames** [ExodiusStudios/vscode-comment-anchors#10]
The extension seems to only highlight when you have a ~~non-whitespace~~ character after the tag:
![image](https://user-images.githubusercontent.com/7832163/46157470-02c21b80-c239-11e8-9645-3eed37ff8482.png)

It also highlights when the tag isn't part of a comment, but I'm not sure if there's an easy way to fix that so I just set matchCase to true.

Edit: It seems to have to be a number, letter, or underscore:
![image](https://user-images.githubusercontent.com/7832163/46157890-f4283400-c239-11e8-8ea2-7dae02d15042.png)

**Comment by macjuul** [comment]
The matching can indeed be improved on yeah. I'll see if I can come up with a better regex to match tags more accurately (Any suggestions on how it should work are welcome!).

As for the variable being matched, unfortunately VS Code lacks an API that allows me to detect whether a tag is in a comment or not (quite ironic for an extension calling itself **comment** anchors, heh). I'm still looking for a way to fix this, however it doesn't look like VS Code will be implementing such API anytime soon.

**Comment by GammaGames** [comment]
I think the easiest way to fix it would only allow a handful of non-whitespace characters in front of the tag on anchors. The longest I can think of is `<!--` in HTML, I couldn't get a regex written myself but I asked on StackOverflow and someone got me [this](https://regex101.com/r/x4EA4g/3)

It allows 0-10 non-whitespace characters before the tag with any amount of whitespace in between the non-whitespace characters. I think that might work better, but I haven't looked into the extension to see how its regexes work yet.

**Comment by macjuul** [comment]
Thanks! I've tried my hand at a better regex as well

![regex](https://user-images.githubusercontent.com/7606171/46198914-dc21e480-c30d-11e8-8cca-0ddf08837940.png)

I'll still have to do a bunch of testing but I believe this regex matches quite accurately. Might still have to tweak it a bit
