### ISSUE TITLE
Flat icon style suit VS code

### ISSUE THREAD

**Issue by FradSer** [ExodiusStudios/vscode-comment-anchors#100]
Here is the flat style icon:
![anchor_black](https://user-images.githubusercontent.com/1439628/96474824-ca4d6a00-1265-11eb-80a6-f581fb5dd4b0.png)
In activity bar looks like:
<img width="429" alt="image" src="https://user-images.githubusercontent.com/1439628/96474490-70e53b00-1265-11eb-8f2a-330e4627e045.png">

**Comment by JordanDi123** [comment]
We actually prefer the way the current icon looks as opposed to this one.

Thank you for your suggestion though!
