### ISSUE TITLE
Document sliding up when comment with link behaviour is present in it

### ISSUE THREAD

**Issue by InsalataCondita** [ExodiusStudios/vscode-comment-anchors#109]
I was using link behavioured comments in order to keep trace of eventually duplicated strings and I noticed that writing code the document started to slide up

This is the comments configuration:

```
{
      "tag": "TODO",
      "iconColor": "blue",
      "highlightColor": "#3ea8ff",
      "scope": "workspace"
    }
```

this is instead a comment example: 

```
     //GOTO  - localization.ts:31
    //DS - commissionManaging: "Gestione commissioni"
```

I hope this is enought to understand what's wrong

**Comment by hugows** [comment]
Yep - had to uninstall the otherwise genius extension due to this issue. I was very lucky to find the culprit for this, because the behaviour is subtle.

**Comment by JordanDi123** [comment]
Spent some time today looking into this one. @macjuul tried it himself and could not reproduced on his end but I was able to on mine. He attempted a fix but it did not solve the problem just yet. I did however find a temporary fix is simply clicking into another file and switching back. Will give it another go at a later time.

**Comment by JordanDi123** [comment]
In the newest release (v1.9.5), we changed the way LINK tags work. They no longer use CodeLens and instead use DocumentLinks and as a result, that also fixes this problem. 

Thank you for using Comment Anchors!
