### ISSUE TITLE
Place tag highlight to the right in the scrollbar ruler

### ISSUE THREAD

**Issue by AlanCutFlim** [ExodiusStudios/vscode-comment-anchors#110]
Currently comment-anchors put tag highlight on the left side of the scrollbar ruler, but the left side area often contains vscode build-in git highlight, in this case it will mix them up(pointed in the image) which will make people like me confused.
![image](https://user-images.githubusercontent.com/50612752/106998570-adf71e00-67bf-11eb-8d9a-8e6b8037f3cd.png)

I think it will be better and clearer to place tag highlight to the right in the scrollbar ruler. 
![image](https://user-images.githubusercontent.com/50612752/106998588-b3546880-67bf-11eb-839a-ff04010e4d1a.png)

**Comment by macjuul** [comment]
Thanks for your issue!

You should be able to change the positioning of the ruler highlight with the `commentAnchors.tags.rulerStyle` setting, or optionally disable it with the `commentAnchors.tags.displayInRuler` setting.

**Comment by AlanCutFlim** [comment]
Thanks! It helps me a lot.
