### ISSUE TITLE
Does Comment Anchor support VS 2017?

### ISSUE THREAD

**Issue by markyoung143** [ExodiusStudios/vscode-comment-anchors#111]
I could not find this in the documentation. It does not install on my system.
If it does not support, can it be made to support it?

[VSIXInstaller_61b4d8d2-8970-4cf6-a7a4-071263444a7e.log](https://github.com/ExodiusStudios/vscode-comment-anchors/files/5974656/VSIXInstaller_61b4d8d2-8970-4cf6-a7a4-071263444a7e.log)

**Comment by macjuul** [comment]
Comment Anchors is an extension for Visual Studio Code and as far as I know Visual Studio offers no compatibility at this time.

**Comment by markyoung143** [comment]
I interpret "Comment Anchors is an extension for Visual Studio Code and as far as I know Visual Studio offers no compatibility at this time." as double talk. Unless Visual Studo Code and Visual Studio are somehow different things, this makes no sense. If you provide a VSIX installer, then it is "for" Visual Studio - saying Visual Studio "offers no compatiblity" sounds like VS is not compatible with Comment Anchor, but it must be the other way around?

**Comment by macjuul** [comment]
Visual Studio, the IDE, and Visual Studio Code, the code editor, are two completely different projects and besides sharing the same packaging format (VSIX, as they are both Microsoft projects), they share no extensions in common. The reasoning behind reusing the VSIX format is unknown to me and questions regarding it should be directed at Microsoft, not Comment Anchors.
