### ISSUE TITLE
Epic anchors not working

### ISSUE THREAD

**Issue by Jolly-ROC** [ExodiusStudios/vscode-comment-anchors#117]
![image](https://user-images.githubusercontent.com/56179268/116554674-78973380-a8c9-11eb-962f-a0ee34d7f32b.png)
Tried a variety of solutions including copying the example exactly, restarting VS code, and hunting through extension setting for relevant options, but I just can't get epic anchors to work.

**Comment by JordanDi123** [comment]
This works as intended as epics only work with workspace scoped tags.

To change the scope of a tag, you can change the workspace from `file` to `workspace` in the `settings.json` file:

![image](https://user-images.githubusercontent.com/24500399/118411890-f185e180-b664-11eb-96ca-0aac84d2f60f.png)

Regardless, thank you for the report. Thank you for using Comment Anchors! 👍

**Comment by Jolly-ROC** [comment]
Thanks, might be good to include a footnote on that when describing the feature, as the default settings after installing the extension prevented epic anchors from working when following the documentation example

Keep up the good work, thanks for the great extension
