### ISSUE TITLE
SUGGESTION: Enlapse Anchors sections by default.

### ISSUE THREAD

**Issue by Maelep** [ExodiusStudios/vscode-comment-anchors#118]
I would like to suggest to enlapse Anchors Sections by default.

![image](https://user-images.githubusercontent.com/53207714/116915124-e934ac00-ac4b-11eb-855d-5435d293903f.png)

TO

![image](https://user-images.githubusercontent.com/53207714/116915145-f0f45080-ac4b-11eb-967d-d1649b6fecb8.png)

**Comment by JordanDi123** [comment]
Thank you for the suggestion!

This has been implemented and will be available in the next update! :)

**Comment by Maelep** [comment]
Thank you a lot!
