### ISSUE TITLE
Links to Archers on the Same Page 

### ISSUE THREAD

**Issue by JoeyAtkinson** [ExodiusStudios/vscode-comment-anchors#120]
**As a** Developer
**I Want** for LINK to point to ANCHOR in the _same_ file
**So That I** can support SEE in comments, and support better commenting within the same file

For example:

```
# self.py

          > Click here to open file at anchor wildcards  <---- doesn't work. 
line 100: # LINK ./self.py#link_in_same_file

          # preferably, when its the same document, just assume its an id if no / or .
line 110: # LINK link_in_same_file

...

link 900: # ANCHOR[id=link_in_same_file]
```

Works find if it a different file, but not the same file. Also note, it will work in the same file with line numbers. The reason this is useful is for larger files, and writing documentation.

Preferably, sense file names can change, for self links, `# LINK link_in_same_file` when its in the same file would give a better user experience. 

Do this for me, I will buy you a coffee.

**Comment by JordanDi123** [comment]
The bug has been fixed and will be available in the next update.

Thank you for the report!

P.S. I will be expecting a coffee ;)
