### ISSUE TITLE
Option to show cursor location among anchors

### ISSUE THREAD

**Issue by sloganking** [ExodiusStudios/vscode-comment-anchors#122]
While the ``comment anchors`` sidebar provides a nice overview of how a file's code is organized, it does not display the current location of the user's cursor relative to the comment anchors. In order for the user to find out what part of the code they are inside of, they must scroll up until they see a comment anchor, and then find that comment anchor's comment name inside the comment anchors sidebar.

![](https://i.imgur.com/lAiDghD.png)

This issue proposes a toggle-able option that will inject a comment anchor icon for the user's cursor into the sidebar, and always unfold any sections necessary to display that icon in the sidebar. A button for this icon could be put next to the existing ``collapse all`` button.

Here are some visual examples using a REVIEW anchor in place of the proposed automated USER anchor.

![](https://i.imgur.com/wrZfGYi.png)

![](https://i.imgur.com/kPtK3e2.png)
![](https://i.imgur.com/EnxvSAs.png)

Visually, this issue proposes the USER anchor look like the above images, except that the ``REVIEW`` text would either be dropped or replaced by ``USER`` and the green anchor would be replaced by a more traditional user icon. Similar to the image below.

![](https://cdn1.iconfinder.com/data/icons/ui-5/502/profile-512.png)

**Comment by macjuul** [comment]
Hey!

I've gone ahead and implemented your suggestion, I hope it's as you expected it to be!

Thanks!

![image](https://user-images.githubusercontent.com/7606171/119273120-b27a0200-bc09-11eb-96c8-8479280f15d8.png)

**Comment by sloganking** [comment]
@macjuul Thanks for the speedy response, that looks great! I'd like to verify this change's behavior, however the latest commit I can see in this repo is from 7 days ago. Is there a way I can try out this fix now, or will I need to wait until this change is merged into the live extension?

**Comment by sloganking** [comment]
I see this fix has now been put in https://github.com/ExodiusStudios/vscode-comment-anchors/commit/d5741ae9aab18f8d98c0408c66512565e4562749 and is contained in release 1.9.4 . Ending this discussion for now.
