### ISSUE TITLE
FAQ/ Feature Request / Feedback

### ISSUE THREAD

**Issue by waleedrana777** [ExodiusStudios/vscode-comment-anchors#129]
I want to ask if the entire comment line after a tag can be highlighted or any settings exists to enable/disable that.

Also It would be nice if I could only see the colour of the anchor in the side bar instead of the icon and the text of what tag it is! Maybe a setting to enable that?! 

Line number can stay in there! I made the concept in the image below. It would make the UI much more cleaner and less clutter of repetitive stuff!

![image](https://user-images.githubusercontent.com/37755440/130142178-e4f68d43-66b7-4cfd-bbba-5b75011444d3.png)

**Comment by macjuul** [comment]
Hello!

While I would love to implement this as feature I'm fairly certain vscode's extension API unfortunately does not provide us with a way to change the color of the file tree item text. I'll label this accordingly so we can keep track for future reference.

Thanks for your suggestion though!
