### ISSUE TITLE
Cannot set breakpoints on lines with anchor

### ISSUE THREAD

**Issue by cujslive** [ExodiusStudios/vscode-comment-anchors#14]
Cannot set breakpoints on lines with anchor. Breakpoint area is not clickable if an anchor is present in the line. I can set the breakpoint by a shortcut but that breakpoint is not showing up on the left side.

![screen shot 2018-10-02 at 9 56 48 pm](https://user-images.githubusercontent.com/35224957/46362539-28fb1780-c68e-11e8-80f6-2aa4da0fc29e.png)

**Comment by macjuul** [comment]
Hi,

Unfortunately this seems like an issue in VS Code itself and the way it handles gutter icons. The best I can do is add the possibility to disable them.
