### ISSUE TITLE
Allow disabling some of the tags

### ISSUE THREAD

**Issue by sloth3toe** [ExodiusStudios/vscode-comment-anchors#15]
I may use the words "note" and "section" in a writing, and so wouldn't want them to be considered "tags". Simply removing them from the tag list doesn't seem to do anything:

```
    "commentAnchors.tags.list": [
        {
            "tag": "ANCHOR",
            "iconColor": "default",
            "highlightColor": "#A8C023",
            "scope": "file"
        },
        {
            "tag": "TODO",
            "iconColor": "blue",
            "highlightColor": "#3ea8ff",
            "scope": "workspace"
        },
        {
            "tag": "FIXME",
            "iconColor": "red",
            "highlightColor": "#F44336",
            "scope": "workspace"
        },
        {
            "tag": "STUB",
            "iconColor": "purple",
            "highlightColor": "#BA68C8",
            "scope": "file"
        }
    ]
```

**Comment by Densorius** [comment]
You can already disable a anchor by adding enabled and set it to false like this `"enabled: false"`.

**Comment by sloth3toe** [comment]
Got it. Thanks! And I suppose that new tags can be added as well?

**Comment by macjuul** [comment]
Thats right! You can check the README for instructions on how to further use and configure this extension

**Comment by sloth3toe** [comment]
Thanks! The "enabled" property wasn't mentioned I believe, so maybe it's worth it to update the Readme. And there's no explicit example to add a new tag even though I think I could guess that.

**Comment by macjuul** [comment]
> 
> 
> Thanks! The "enabled" property wasn't mentioned I believe, so maybe it's worth it to update the Readme. And there's no explicit example to add a new tag even though I think I could guess that.

My apologies, I've indeed forgot to mention it. Thanks!
