### ISSUE TITLE
How to use Anchor for HTML comments?

### ISSUE THREAD

**Issue by AdmiralYenga** [ExodiusStudios/vscode-comment-anchors#160]
Hey, I hope you're doing well!

I wanted to use Anchor comments for my HTML comments, but it doesn't work at all. My settings are on standard, and I didn't optimized them at the moment.
I hope someone can help me with that, and answer my question about how to use this tool for HTML comments.

Kind regards

Yenga

**Comment by JordanDi123** [comment]
Hi! 

I'm doing great, thanks for asking! I hope you are well as well! 😄

You can leave anchors within HTML comments by using one of the keywords. Here's an example of a TODO anchor as shown on line 10:

![image](https://user-images.githubusercontent.com/24500399/214144261-1582e1cc-00ff-4665-a3bb-2d79646afccc.png)

Please ensure you have an open workspace (i.e., you opened a folder and are working from in there as opposed to just opening a random .html file on its own) 

Hope that helps!

**Comment by KariCodesHere** [comment]
I'm also having issues in HTML. No anchors will show up in HTML, every other language works.

**Comment by TicSo** [comment]
<img width="470" height="354" alt="Image" src="https://github.com/user-attachments/assets/e9e0c095-a8ed-42da-b36a-be672cc5ba3b" />
