### ISSUE TITLE
Unwanted behavior in (possibly) RTL languages

### ISSUE THREAD

**Issue by babakks** [ExodiusStudios/vscode-comment-anchors#20]
Hi,

I just noticed the extension does not detect anchors that are followed by non-english text. I hadn't this problem before, so I think it's the new modifications.

![bug](https://user-images.githubusercontent.com/36728931/46786306-55bfc680-cd41-11e8-91bf-c575f2660fb3.png)

**Comment by macjuul** [comment]
A fix will be released shortly (See https://github.com/ExodiusStudios/vscode-comment-anchors/issues/17)
