### ISSUE TITLE
Add paths to exclude config option

### ISSUE THREAD

**Issue by lonix1** [ExodiusStudios/vscode-comment-anchors#22]
The exclude config option `"commentAnchors.workspace.excludeFiles"` has this default:

    "**/{node_modules,.git,.idea,target,out,build,vendor}/**/*"

I tried to add `.gitignore` file:

    "**/{node_modules,.git,.idea,target,out,build,vendor}/**/*, .gitignore"

But that doesn't work - it just scans forever.

**Comment by macjuul** [comment]
Hey, this seems more of a limitation of glob patterns and does not seem possible at this time. Adding a custom filtering solution may be implemented in the future, however it is not currently planned
