### ISSUE TITLE
[Feature request] Add options for hiding tag text and line number ,and customizable font size for side bar

### ISSUE THREAD

**Issue by tete1030** [ExodiusStudios/vscode-comment-anchors#26]
![image](https://user-images.githubusercontent.com/4312115/48976378-5b8b2480-f0c1-11e8-86fa-8aff320071bf.png)

Thank you for your great extension. I really like the anchor side bar. But I prefer a small size one and after I resized it to smaller, useful information will be hided. I think the `TODO` text in this case is not necessary since the color has already indicate its category. The line number is also unnecessary for me since I use the side bar by clicking on an item. So I think these styles should be customizable for users with different needs.

Besides, if the font size for side bar can be smaller or customizable, the side bar can show more information.

Thank you!

**Comment by tete1030** [comment]
Thank you very much, @heronils . I will try to dig the font size workaround and let you know. And when I have some time, maybe I will read the code and make a pull request of these features.

**Comment by heronils** [comment]
@tete1030 you´re welcome

**Comment by macjuul** [comment]
Hey, sorry for the delay,

Hiding tag names from the sidebar is already possible, by setting `commentAnchors.tags.displayInSidebar` to  false. A setting to hide line numbers will be added in the next release.

Thanks!
