### ISSUE TITLE
Not support HTML comment

### ISSUE THREAD

**Issue by LasyIsLazy** [ExodiusStudios/vscode-comment-anchors#30]
`<!-- TODO something -->` will show nothing in FILE ANCHORS.

**Comment by macjuul** [comment]
Hey!

I'm unable to reproduce your issue, however this may be caused by the tags separator option (`commentAnchors.tags.separator`). Would it be possible to check if you have the option set, and if so share it with me?

Thanks!

**Comment by LasyIsLazy** [comment]
Thanks for your reply! Now it shows, but I do nothing. I'm unable to reproduce this issue, either. If this happen again, I will back to this issue.
