### ISSUE TITLE
[Feature request] Total number of anchors

### ISSUE THREAD

**Issue by mittalyashu** [ExodiusStudios/vscode-comment-anchors#33]
This extension is very helpful, but the problem is that when you come back after a long time to a project and forget everything about the project, even if you have added any comment anchor or not.

In that case, it would be helpful to see a notification number, that how many total number of comment anchor we have.

![image](https://user-images.githubusercontent.com/29014463/49605340-39917c00-f9b6-11e8-98f0-062073601ffc.png)

**Comment by duranivan** [comment]
I was thinking exactly the same thing. This would be really helpful for the same reasons that @mittalyashu mentions!

**Comment by macjuul** [comment]
Hey,

As much as I would love to add this, it does not seem currently possible (See https://github.com/Microsoft/vscode/issues/62783). If this API were to be added, I'll implement support for it as soon as possible.

Thanks!

**Comment by mittalyashu** [comment]
Thanks for the update @macjuui.

Can you keep this issue open so in future we are aware of this feature request?

And it will also avoid duplication of issue _(features request)_
