### ISSUE TITLE
isWholeLine

### ISSUE THREAD

**Issue by GammaGames** [ExodiusStudios/vscode-comment-anchors#4]
Hello!

You mentioned that you released an update that had this feature in the other issue, but I don't see the option anywhere. Am I just blind?

**Comment by macjuul** [comment]
My bad, sorry for not mentioning it more clearly. I called the property "styleComment", since it styles slightly more intelligently than "isWholeLine".

**Comment by GammaGames** [comment]
Oh, so it only styles the comment instead of the whole line? I guess since I have the gutter icons the whole line isn't as necessary, feel free to close if that is the case.
