### ISSUE TITLE
Certain characters don't show up in the anchor list if they are as last character(s)

### ISSUE THREAD

**Issue by DeltaRazero** [ExodiusStudios/vscode-comment-anchors#45]
Certain characters will not show up in the anchors list when they are used as last character.
I am not sure if there are more, but this should give a good insight into what I mean.

**As last character(s):**
![image](https://user-images.githubusercontent.com/26445643/54686057-ad483680-4b18-11e9-8373-225745e06055.png)
![image](https://user-images.githubusercontent.com/26445643/54686183-fdbf9400-4b18-11e9-8155-9c36c6e1957b.png)

**However, append it with letters or an underscore and there is no problem:**
![image](https://user-images.githubusercontent.com/26445643/54686365-6870cf80-4b19-11e9-9a79-f1197a35b8ba.png)
![image](https://user-images.githubusercontent.com/26445643/54686383-74f52800-4b19-11e9-9266-1eb588bdc92a.png)

**The usecase where I would encounter this bug:**
![image](https://user-images.githubusercontent.com/26445643/54686274-2e073280-4b19-11e9-93ea-8f69b7b80d0e.png)

**Comment by macjuul** [comment]
Fixed as of 1.7.0
