### ISSUE TITLE
option to not show on scrollbar

### ISSUE THREAD

**Issue by dwelle** [ExodiusStudios/vscode-comment-anchors#48]
Allow to disable show-on-scrollbar, which clutters the UI and you're not sure if it's a lint error, git change, or an anchor.

![image](https://user-images.githubusercontent.com/5153846/55968478-57306400-5c7c-11e9-8216-eb3fc17c98fb.png)

**Comment by kxu-ffd** [comment]
I have the same issue that the scrollbar highlights for the comment anchors become too overwhelming. I am working on a large project with multiple contributors. Everyone is using TODO's and FIXME's and with this extension enabled, my scrollbar basically is filled with highlight color blocks. I wish it would allow the user to customize the scrollbar highlights separately so we could use colors that are more subtle or disable the scrollbar highlights without affecting highlights in the code.

**Comment by macjuul** [comment]
Added a new setting for this for the next update of Comment Anchors
