### ISSUE TITLE
Extension breaks folding in Python

### ISSUE THREAD

**Issue by DeltaRazero** [ExodiusStudios/vscode-comment-anchors#52]
This extension breaks the folding buttons in VSCode in Python. Please fix, thank you very much.

**Comment by DeltaRazero** [comment]
?

**Comment by GammaGames** [comment]
Have you tried disabling folding in the extension? I had a similar issue in #13

**Comment by bitsy** [comment]
@DeltaRazero I suggested the same thing in #61 ... disabling editor folding for Comment Anchors in User Settings seems to solve the issue (of course, then you won't be able to fold your anchors).

**Comment by macjuul** [comment]
Fixed as of 1.7.0 due to the removal of editor folding.
