### ISSUE TITLE
Is it possible to exclude files by file suffix?

### ISSUE THREAD

**Issue by LuckyRabbitFeet** [ExodiusStudios/vscode-comment-anchors#57]
There are a lot of `.map` files in the project being scanned, which causes the scan to be very card. I tried to add `.map` in the exclude config option, but that doesn't work.

**Comment by HaaLeo** [comment]
One possible approach could be to allow the `"commentAnchors.workspace.excludeFiles"` setting to be either a _string_ or an _array_ of strings. This could be achieved via the json schema for that setting.
