### ISSUE TITLE
Show file icons for each file in workspace view

### ISSUE THREAD

**Issue by GammaGames** [ExodiusStudios/vscode-comment-anchors#6]
Hello again!

I think it would be nice to show the file's icon in the user's icon theme (for example, I use this: https://marketplace.visualstudio.com/items?itemName=PKief.material-icon-theme) instead of the general file icon. Hopefully they have an API for getting file icons by type, or something similar

**Comment by macjuul** [comment]
Hey,

It does not look like it is currently possible to implement this, as they unfortunately do not have an API for getting icons by file type ([link](https://github.com/Microsoft/vscode/issues/10804#issuecomment-326533897)).

Thanks for your suggestion though!
