### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by timrcoder** [ExodiusStudios/vscode-comment-anchors#60]
I would like to create tag names.  I cannot find configuration in order to do this?

**Comment by alexandrugatea** [comment]
Hello @timrcoder 
Have you tried (in settings.json):
    "commentAnchors.tags.list": 
    [
        {
            "tag"            : "Read Me",
            "iconColor"      : "green",
            "highlightColor" : "green",
            "backgroundColor": "none",
            "scope"          : "file",
            "isBold"         : true,
            "isItalic"       : true
        }
    ]

**Comment by macjuul** [comment]
Closing as the question has been answered correctly.
