### ISSUE TITLE
Does not scan SSHFS

### ISSUE THREAD

**Issue by raffaeletani** [ExodiusStudios/vscode-comment-anchors#63]
Doesn't work with filesystems mountet with the [SSHFS ](https://marketplace.visualstudio.com/items?itemName=Kelvin.vscode-sshfs) extension: 

tried with lazy-loading on and off

If the file is once opened, the anchors get registered and listed properly.

Clicking on such an anchor prompts you to save your workspace, closes the workspace and opens a new workspace with the name of the clicked file ( see https://youtu.be/R95u-dMLJBo )

**Comment by macjuul** [comment]
Working fine for me when SSH'd into an Ubuntu VPS, so I assume it's working on the latest version of Comment Anchors. Feel free to report back if the issue persists.
