### ISSUE TITLE
Set Comment Anchors collapse/expand feature to false by default

### ISSUE THREAD

**Issue by marvinhosea** [ExodiusStudios/vscode-comment-anchors#67]
Comment Anchors collapse/expand feature conflicts with VSCode collapse/expand feature and for someone starting out it can drive you nuts and waste your time figuring out how to solve that.

Code block folding is highly required as compared to Anchor feature hence make Anchor folding feature disabled/false by default

**Comment by asmallgod** [comment]
I agree it, but how to solve this problem?

**Comment by billmind** [comment]
Can anyone help with that i have also same problem

**Comment by billmind** [comment]
For Solution Please See #61

**Comment by macjuul** [comment]
I'm planning on removing this feature all together in the next update as it has caused more harm than good. As @billmind mentioned the best course of action is to disable anchor collapsing all together using the setting.
