### ISSUE TITLE
Default exclusion glob pattern

### ISSUE THREAD

**Issue by babakks** [ExodiusStudios/vscode-comment-anchors#7]
Hi,

Sadly, the default exclusion glob pattern doesn't mention the "node_modules" directory. This caused VS Code to be terribly slow. I checked everything and spent more than an hour to figure out the problem was caused by the extension. Since, in the new versions, the extension looks for anchors throughout the workspace, and sadly, the default file exclusion glob pattern doesn't take "node_modules" directory into account, it had no choice but checking all modules. I fixed this, by updating my exclusion glob pattern like this:
`{node_modules,.git,.idea}/**/*`

Please update the defaults to save others' time.

**Comment by macjuul** [comment]
Ah yes, I unfortunately did not notice that because VS Code was already excluding node_modules from my project, I'll make a quick hotfix and release it today.

Thanks for your issue!

**Comment by gsabater** [comment]
That is a good start for performance.

I would also propose an additional option to enable/disable the workspace scan on startup.
Maybe a command to perform the scan would be more useful.

A word about performance, i don't know how the scan is performed, but looks like vscode is actually opening all the files, and setting the CPU on 100% leaving the machine almost unusable for a minute or more. The problem with opening files is that other extensions like phpinteliphense perform their actions as well.

There are another extension called todo+ that has a command to parse all todo's (fixme, readme, etc) in the whole project, and has the result in mere seconds without opening a single file, or at least, vscode dont perform opening operations.

**Comment by babakks** [comment]
Just one more thing: please correct "matchFiles" in `README.md`, which should be "excludeFiles" instead.

**Comment by macjuul** [comment]
> 
> 
> That is a good start for performance.
> 
> I would also propose an additional option to enable/disable the workspace scan on startup.
> Maybe a command to perform the scan would be more useful.
> 
> A word about performance, i don't know how the scan is performed, but looks like vscode is actually opening all the files, and setting the CPU on 100% leaving the machine almost unusable for a minute or more. The problem with opening files is that other extensions like phpinteliphense and linting perform their actions as well.
> 
> There are another extension called todo+ that has a command to parse all todo's (fixme, readme, etc) in the whole project, and has the result in mere seconds without opening a single file, or at least, vscode dont perform opening operations.
> 
> I don't want to hijack an issue, if you @macjuul think that those comments should be a new issue, just move it or tell me.

I'm currently working on a fix that changes the way files are loaded and scanned, which should solve that. I'll also implement a setting to disable workspace anchors for those who aren't interested in it.



> 
> 
> Just one more thing: please correct "matchFiles" in `README.md`, which should be "excludeFiles" instead.

Woops, will fix!
