### ISSUE TITLE
Not be able to make this tag

### ISSUE THREAD

**Issue by VrTech** [ExodiusStudios/vscode-comment-anchors#72]
![custom-tags](https://user-images.githubusercontent.com/19533090/76345867-52779400-62c1-11ea-818d-7629c61684c6.png)

How to make a custom tag like this?

I tried above but comments aren't highlighted

**Comment by macjuul** [comment]
Are you sure you added the custom tag to the `commentAnchors.tags.list` array?

![image](https://user-images.githubusercontent.com/7606171/76346956-1c103800-6306-11ea-9da6-d50d05560ad6.png)

**Comment by VrTech** [comment]
I did. However, it show on me like this instead.

<img width="524" alt="Screen Shot 2020-03-10 at 1 57 10 PM" src="https://user-images.githubusercontent.com/19533090/76358686-0fc0b680-62d7-11ea-9f05-6c035f4c5f6b.png">

**Comment by macjuul** [comment]
It looks like you may have misspelled `styleComment` as `styledComment` 😉

**Comment by VrTech** [comment]
> It looks like you may have misspelled `styleComment` as `styledComment` 😉
My BAD :P
Thank you! So much appreciated!
