### ISSUE TITLE
Folding not working in latest VSCode

### ISSUE THREAD

**Issue by mig8447** [ExodiusStudios/vscode-comment-anchors#75]
Thanks for this extension, it helps a lot. I came across the folding feature for sections but I cannot make it work, fold controls are not shown, and for some reason in an empty JS document they only appear on the top SECTION in the hierarchy. Hope this can be fixed. Thanks.

**Comment by macjuul** [comment]
In-editor folding was removed in the last update due to the numerous issues it caused (#49, #52, #61)

Section folding does still works in the anchor sidebar, however.
