### ISSUE TITLE
Parenthesis not supported ?

### ISSUE THREAD

**Issue by Prn-Ice** [ExodiusStudios/vscode-comment-anchors#81]
Tried creating the tag `TODO(Prn-Ice):` but it doesn't get picked up, I tried to add `(` to the list of valid separators for `TODO`, still nothing.

**Comment by EricChen1248** [comment]
Same here, I cannot get it to work. Doesn't work with a space in between TODO and the parenthesis either, like `// TODO (something)`. My team uses TODO plus parenthesis to tag who the todo is for, but this makes it unable to work with this extension.

**Comment by JordanDi123** [comment]
Hello,

Comment anchors unfortunately does not currently support parenthesis as it would further complicate the regex. If you would like to give it a go and make a pull request, we would be happy to take a look at it. 

Thank you for your interest in Comment Anchors and have a wonderful day!
