### ISSUE TITLE
Use file icon theme setting

### ISSUE THREAD

**Issue by FradSer** [ExodiusStudios/vscode-comment-anchors#83]
I'm using [`vscode-icons`](https://marketplace.visualstudio.com/items?itemName=vscode-icons-team.vscode-icons) as file icon theme  like this:
![image](https://user-images.githubusercontent.com/1439628/84463330-fcd9cb80-aca3-11ea-83c8-875deebd18b6.png)
And icon display in workspace anchors is like this:
![image](https://user-images.githubusercontent.com/1439628/84463344-0b27e780-aca4-11ea-817c-1ace67aa7f49.png)

I think the icon display in workspace anchors should follow the file icon theme setting.

**Comment by macjuul** [comment]
This doesn't appear to be currently possible within VSCode. I made some adjustments where the workspace tree will now use the basic file icon used by the current icon theme, however rendering specialized file icons for specific extensions does not seem possible.
