### ISSUE TITLE
[Feature Request] Highlight sections with children / Expand All

### ISSUE THREAD

**Issue by gabriele-cannizzaro** [ExodiusStudios/vscode-comment-anchors#89]
Hi, thank you for creating an incredibly useful extension. I would like to suggest the option (or default behaviour) to have a SECTION anchor in the navigation panel only show the expansion arrow if it has other anchors inside. I have a file with about 20 sections, but only one or two at a time have TODO or FIXME anchors inside. At the moment I can't see which one without clicking each section to open it.

An alternative or complementary feature would be the option to expand all sections with 1 click.

Thank you!

**Comment by dragonitaq** [comment]
I immediately look for "Expand All" button when I start using it. It is much needed when you have many sections and tags. gabriele-cannizzaro's suggestion is solid and I appreciate if such feature available. Thank creator.

**Comment by macjuul** [comment]
Would love to add this feature, unfortunately it doesn't appear to be possible at this time (See https://github.com/microsoft/vscode/issues/88682)

Will implement this once the VSCode Extension API allows for it.

**Comment by macjuul** [comment]
Will close this issue for now for housekeeping sake since VSCode unfortunately still does not support this
