### ISSUE TITLE
Suggestion: Match upper and lowercase

### ISSUE THREAD

**Issue by gsabater** [ExodiusStudios/vscode-comment-anchors#9]
Hello,

When working with other people, sometimes your coworkers write todos and note comments but the keyword is in lowercase.

If the performance hit for checking both upper and lowercase is not too big, it would be very nice that the `TODO:` key can be matched with `todo:` as well.

Ideally, this could be done without adding the lowercase key to the settings, or we could end with a VERY large array of settings in our file if we want to add another key. 

Maybe make the `commentAnchors.tags.list` setting additive instead of replacing the default keys

**Comment by macjuul** [comment]
Good news, I'll be able to add case insensitive matching without any required config changes (I'll probably make a setting to disable it still). If I have time I'll see if I can sneak it into a release later today or tomorrow together with the important performance fix.

As for changing the way `commentAnchors.tags.list` works, I'll look into that in the future, as giving people the freedom to disable/remove the default anchors is important as well

Thanks!

**Comment by gsabater** [comment]
Awesome news.
You are right about the default tags list. Maybe the setting is good as is.

Thanks for everything, you are doing a good job here
