### ISSUE TITLE
[Feature Request] Publish on Open VSX Registry

### ISSUE THREAD

**Issue by saaymeen** [ExodiusStudios/vscode-comment-anchors#95]
Using Comment Anchors with VSCode is great, but it's hard to get the package in the default configuration of VSCodium because it's not in the [ovsx](https://open-vsx.org/) registry. According to an [issue](https://github.com/VSCodium/vscodium/issues/337#issuecomment-685731017) on their page, publishing the package should be fairly simple.

**Comment by macjuul** [comment]
https://open-vsx.org/extension/ExodiusStudios/comment-anchors

That should've done the trick 🙂

**Comment by saaymeen** [comment]
Thanks man, already installed and working just as expected :+1:

**Comment by chromey** [comment]
Hey. Any chance you could publish the most recent version of the extension as well? Would be much appreciated!
