### ISSUE TITLE
Incorrect match for "LINK" anchor

### ISSUE THREAD

**Issue by WilliamVenner** [ExodiusStudios/vscode-comment-anchors#97]
![image](https://user-images.githubusercontent.com/14863743/94371133-0c164500-00ec-11eb-90b3-0413f97913e5.png)

Language is Lua.

**Comment by macjuul** [comment]
Hello!

Sometimes the default configuration doesn't always work for each project or language. In this case I would suggest tweaking your global or workspace settings and alter the `commentAnchors.tags.separators` list to force anchors to be followed by a specific pattern, such as a colon.

![image](https://user-images.githubusercontent.com/7606171/94413153-fac84980-017a-11eb-8c96-2e69910ad94f.png)
